# Python CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-python/ for more details
version: 2
jobs:
  build:
    machine: true

    steps:
    - checkout

    # build the application image
    - run: docker build -t $DOCKER_USER/ml_recsys_tools:$CIRCLE_BRANCH .

    - run: docker run --rm $DOCKER_USER/ml_recsys_tools:$CIRCLE_BRANCH python -m unittest

    # deploy the image
    - run: |
        if [ "${CIRCLE_BRANCH}" == "master" ]; then
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker tag $DOCKER_USER/ml_recsys_tools:$CIRCLE_BRANCH $DOCKER_USER/ml_recsys_tools:latest
          docker push $DOCKER_USER/ml_recsys_tools:latest
        fi
